### PR TITLE
Add support for SRAM vectors

### PR DESCRIPTION
**Pull request by deividAlfa**

### CODE REVIEW

**Comment by prosper00** [comment]
Cool investigation. I'd suggest adding this to the Makefile (maybe commented out?) something like a -DVECT_TAB_SRAM so that the user doesn't have to modify the system c file.

Just my 2c.

**Comment by deividAlfa** [comment]
The original file was intended to be modified so I kept that route.
I personally prefer header files than defining everything in the makefile,

**Comment by deividAlfa** [comment]
Oops I accidentaly closed PR.

**Comment by IOsetting** [comment]
Thank you for the investigation. 
Should SRAM vectors be enabled by default? As it is intended in Puya's SDK.

**Comment by deividAlfa** [comment]
I guess? Also add some notes there so people understand why are we doing this, wasting 192 bytes of RAM.
This fault also happens in the 003 and possibly in the 030.
So there's some issue with external signal interrupts.
Internal generated interrupts, derived from the main clock (pwm, i2c,systick...) doesn't seem to cause any issues.

**Pull request merged**
